Repository cnpm/npminstall, pull requests merged in 2018-12, with the labels that each got.

#284 fix: try to link latest version to top node_modules
  lib/local_install.js
  test/local-install-pkgs.test.js
Labels: bug, semver: patch

#285 feat: support binary mirror replaceHostFiles config
  lib/download/npm.js
  package.json
Labels: enhancement

#287 feat: support dependencies tree
  bin/install.js
  lib/download/npm.js
  lib/format_install_options.js
  lib/install.js
  lib/local_install.js
  test/dependencies-tree.test.js
  test/fixtures/dependencies-tree/.dependencies_tree.json
  test/fixtures/dependencies-tree/package.json
Labels: enhancement

#289 feat: show post isntall scripts error detail message
  lib/local_install.js
  test/fixtures/sub-module-optional-dep-install-fails/package.json
  test/ignore-install-optional-deps-fails.test.js
Labels: enhancement

#290 fix: show every runscript log before run it
  lib/local_install.js
  lib/postinstall.js
  lib/postuninstall.js
  lib/preinstall.js
  lib/prepublish.js
  lib/preuninstall.js
  test/postInstallError.test.js
Labels: bug, enhancement
