Repository cnpm/npminstall, pull requests merged in 2022-03, with the labels that each got.

#383 📦 NEW: Support manifests cache control
  lib/download/npm.js
  lib/format_install_options.js
  lib/get.js
  lib/local_install.js
  test/installGlobal.test.js
  test/peer.test.js
Labels: enhancement, semver: minor

#387 📦 NEW: Support libc field on conditions install
  lib/download/npm.js
  lib/utils.js
  test/utils.test.js
Labels: enhancement, semver: minor

#388 🐛 FIX: Use detect-libc to get libc family
  lib/download/npm.js
  lib/install.js
  lib/utils.js
  package.json
  test/utils.test.js
Labels: bug

#385 feat: upgrade node-gyp@8 to support python3
  package.json
Labels: enhancement, semver: major

#389 🐛 FIX: Reduce http request retry warning message log
  lib/get.js
Labels: enhancement

#392 feat: upgrade node-gyp@9 to support python3
  .github/workflows/ci.yml
  README.md
  package.json
  test/fixtures/install-raw-socket/package.json
  test/get.test.js
  test/install-with-python3.test.js
Labels: enhancement, semver: major

#393 📦 NEW: Support override custom scripts on bug-versions
  lib/download/npm.js
  test/fix-bug-versions.test.js
Labels: enhancement, semver: minor

#394 📦 NEW: Support override custom scripts on bug-versions (#393)
  .github/workflows/ci.yml
  lib/download/npm.js
  test/fix-bug-versions.test.js
Labels: enhancement
