Repository cnpm/npminstall, pull requests merged in 2022-02, with the labels that each got.

#377 fix: npminstall multi-registry options
  bin/install.js
  test/custom-registry.test.js
Labels: bug, semver: patch

#378 fix: skip pruneJSON when package.json file not exists
  lib/uninstall.js
  test/index.test.js
  test/install-vscode.test.js
Labels: bug

#379 test: Create codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: enhancement
